package round_robin;

import java.util.LinkedList;

/**
 * This class implements functionality associated with
 * the CPU unit of the simulated system.
 */
public class Cpu {
	private Process activeProcess = null;
	
	private LinkedList<Process> cpuQueue;
	private long maxCpuTime;
	Statistics statistics;
	
    /**
     * Creates a new CPU with the given parameters.
     * @param cpuQueue		The CPU queue to be used.
     * @param maxCpuTime	The Round Robin time quant to be used.
     * @param statistics	A reference to the statistics collector.
     */
    public Cpu(LinkedList<Process> cpuQueue, long maxCpuTime, Statistics statistics) {
        this.cpuQueue = cpuQueue;
        this.maxCpuTime = maxCpuTime;
        this.statistics = statistics;
    }

    /**
     * Adds a process to the CPU queue, and activates (switches in) the first process
     * in the CPU queue if the CPU is idle.
     * @param p		The process to be added to the CPU queue.
     * @param clock	The global time.
     * @return		The event causing the process that was activated to leave the CPU,
     *				or null	if no process was activated.
     */
    public Event insertProcess(Process p, long clock) {
        cpuQueue.add(p);
        p.addToCpuQueue(clock);
        if (getActiveProcess() == null) {
        	activeProcess = cpuQueue.pop();
        	activeProcess.activateCpu(clock);
        	return generateEvent(p, clock);
        }
        return null;
    }

    /**
     * Activates (switches in) the first process in the CPU queue, if the queue is non-empty.
     * The process that was using the CPU, if any, is switched out and added to the back of
     * the CPU queue, in accordance with the Round Robin algorithm.
     * @param clock	The global time.
     * @return		The event causing the process that was activated to leave the CPU,
     *				or null	if no process was activated.
     */
    public Event switchProcess(long clock) {
    	if (!cpuQueue.isEmpty()) {
    		if (activeProcess != null) {
    			activeProcess.deactivateCpu(clock);
    			cpuQueue.add(activeProcess);		
    		}
    		activeProcess = cpuQueue.pop();
    		activeProcess.activateCpu(clock);
    		return generateEvent(activeProcess, clock);
    	}
    	return null;
    }

    /**
     * Called when the active process left the CPU (for example to perform I/O),
     * and a new process needs to be switched in.
     * @return	The event generated by the process switch, or null if no new
     *			process was switched in.
     */
    public Event activeProcessLeft(long clock) {
        // Incomplete
        return null;
    }

    /**
     * Returns the process currently using the CPU.
     * @return	The process currently using the CPU.
     */
    public Process getActiveProcess() {
        return activeProcess;
    }

    /**
     * This method is called when a discrete amount of time has passed.
     * @param timePassed	The amount of time that has passed since the last call to this method.
     */
    public void timePassed(long timePassed) {
        // Incomplete
    }
    
    public Event generateEvent(Process p, long clock) {
    	if (p.getCpuTimeNeeded() > maxCpuTime && p.getTimeToNextIoOperation() > maxCpuTime) {
    		return new Event(Event.SWITCH_PROCESS, clock + maxCpuTime);
    	}
    	else if (p.getTimeToNextIoOperation() > p.getCpuTimeNeeded()) {
    		return new Event(Event.END_PROCESS, clock + p.getCpuTimeNeeded());
    	}
    	else {
    		return new Event(Event.IO_REQUEST, clock + p.getTimeToNextIoOperation());
    	}
    }

}
